<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
    <div class="header-content">
        <div class="nav-container">
            <h6 class="logo">
                <strong><?php echo $this->getLogoAlt() ?></strong>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
                </a>
            </h6>

            <div class="header">
                <div class="quick-access">
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('topSearch') ?>
                    <div class="quick-access-link">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                    <?php echo $this->getChildHtml('cart_sidebar')?>
                </div>
			
<div class="like-parent"><div data-share-size="20" data-like-text-enable="false" data-background-alpha="0.0" data-pid="1280536" data-mode="share" data-background-color="ededed" data-share-shape="round-rectangle" data-icon-color="ffffff" data-share-counter-size="9" data-text-color="000000" data-buttons-color="ff9300" data-counter-background-color="ffffff" data-share-counter-type="separate" data-orientation="horizontal" data-following-enable="false" data-sn-ids="fb.tw.ok.vk.gp.mr." data-selection-enable="false" data-share-style="1" data-counter-background-alpha="1.0" data-top-button="false" class="uptolike-buttons" ></div></div>
                <?php echo $this->getChildHtml('topContainer'); ?>
            </div>

            <div class="menu-box">
                <?php echo $this->getChildHtml('topMenu', true) ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('delivery_promoter') ?>
