<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
    <div class="header-content">
        <div class="nav-container">
            <h6 class="logo">
                <strong><?php echo $this->getLogoAlt() ?></strong>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
                </a>
            </h6>

            <div class="header">
                <div class="quick-access">
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('topSearch') ?>
                    <div class="quick-access-link">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                    <?php echo $this->getChildHtml('cart_sidebar')?>
                </div>
                <?php echo $this->getChildHtml('topContainer'); ?>
            </div>

            <div class="menu-box">
                <?php echo $this->getChildHtml('topMenu', true) ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('delivery_promoter') ?>
