<div class="category-description-seo">
<div style="display: inline-block;">
<div style="padding-top: 10px; float: left;"><span>Лайкнуть: </span><div data-share-size="40" data-like-text-enable="false" data-background-alpha="0.0" data-pid="1280536" data-mode="like" data-background-color="ededed" data-share-shape="rectangle" data-icon-color="ffffff" data-share-counter-size="11" data-text-color="000000" data-counter-background-color="ffffff" data-share-counter-type="disable" data-orientation="horizontal" data-following-enable="false" data-sn-ids="vk.fb.ok.gp.mr." data-selection-enable="true" data-share-style="1" data-counter-background-alpha="1.0" data-top-button="false" class="uptolike-buttons" ></div></div>
</div>
    <?php
        $_category = Mage::registry('current_category');
        $_helper = $this->helper('catalog/output');
        $_imgHtml = '';
        if ($_imgUrl = $_category->getImageUrl()) {
            $_imgHtml =
                '<p class="category-image">' .
                '<img src="' . $_imgUrl . '" alt="' . $this->htmlEscape($_category->getName()) . '" ' .
                'title="' . $this->htmlEscape($_category->getName()) . '" />' .
                '</p>';
            $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        }
    ?>
    <?php if ($_description = $_category->getDescription()): ?>
        <div class="category-description std">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </div>
    <?php endif; ?>
    <?php if ($_shortDescription = $_category->getShortDescription()): ?>
        <div class="category-description std">
            <?php echo $_helper->categoryAttribute($_category, $_shortDescription, 'short_description') ?>
        </div>
    <?php endif; ?>

    <?php if ($_imgUrl): ?>
        <?php echo $_imgHtml; ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    jQuery(function () {
        var fixerBlock = jQuery('.layout-seo-fixer'),
            textBlock = jQuery('.category-description-seo');

        var fixHeight = function () {
            textBlock.css({
                'text-indent': 0,
                'top':         fixerBlock.offset().top
            });

            fixerBlock.css({
                'height': textBlock.get(0).clientHeight
            });
        };

        fixHeight();
        if (textBlock.find('img').length) {
            textBlock.find('img').load(fixHeight);
        }
    });
</script>
