<div class="page-title category-title">
    <?php if ($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__( 'Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $this->getChildHtml('meta_title') ?></h1>
<script type="text/javascript">(function(w,doc) {
if (!w.__utlWdgt ) {
    w.__utlWdgt = true;
    var d = doc, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == w.location.protocol ? 'https' : 'http')  + '://w.uptolike.com/widgets/v1/uptolike.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
}})(window,document);
</script>
<span>Лайкнуть: </span><div data-share-size="40" data-like-text-enable="false" data-background-alpha="0.0" data-pid="1280536" data-mode="like" data-background-color="ededed" data-share-shape="rectangle" data-icon-color="ffffff" data-share-counter-size="11" data-text-color="000000" data-counter-background-color="ffffff" data-share-counter-type="disable" data-orientation="horizontal" data-following-enable="false" data-sn-ids="vk.fb.ok.gp.mr." data-selection-enable="true" data-share-style="1" data-counter-background-alpha="1.0" data-top-button="false" class="uptolike-buttons" ></div>
<span>Поделится: </span><div data-share-size="30" data-like-text-enable="false" data-background-alpha="0.0" data-pid="1280536" data-mode="share" data-background-color="ededed" data-share-shape="round-rectangle" data-icon-color="ffffff" data-share-counter-size="9" data-text-color="000000" data-buttons-color="ff9300" data-counter-background-color="ffffff" data-share-counter-type="separate" data-orientation="horizontal" data-following-enable="false" data-sn-ids="fb.tw.ok.vk.gp.mr." data-selection-enable="false" data-share-style="1" data-counter-background-alpha="1.0" data-top-button="false" class="uptolike-buttons" ></div>
    <div class="cls_hide-options">
        <div id="div_hide_option" onclick="clickHideOption()">
            <?php echo $this->__('Hide') ?>
        </div>
        <a onclick="clickHideOption()" id="id_page_arrow" href="#" class="page_arrow" title="">&nbsp</a>
    </div>
</div>


<?php if ($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif ($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
<div class="layout-seo-fixer clearfix"></div>

<script>
    function clickHideOption() {
        var $arrow = $('id_page_arrow'),
            $sorterOption = $('sorter_option');
        $arrow.toggleClassName('hidden_arrow');
        $sorterOption && $sorterOption.toggleClassName('hidden_click');
        if ($arrow.hasClassName('hidden_arrow')) {
            $('div_hide_option').update('<?php echo $this->__('Show');?>');
        } else {
            $('div_hide_option').update('<?php echo $this->__('Hide');?>');
        }

        return false;
    }
</script>
